name: likelocal
description: "LikeALocal - Discover authentic local experiences."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  image_picker: ^1.0.0
  permission_handler: ^11.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.0
  connectivity_plus: ^6.0.0
  geolocator: ^12.0.0
  firebase_storage: ^12.1.1
  google_generative_ai: ^0.4.4
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  workmanager: ^0.9.0+3
  flutter_dotenv: ^5.1.0
  flutter_tts: ^4.0.0
  speech_to_text: ^7.3.0


  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansExtraBold.ttf
          weight: 800
